parameters:
    shapecode_twig_collector.twig_extension.collector.class: Shapecode\Twig\Extensions\Extension\Collector

services:
    shapecode_twig_collector.twig_extension.collector:
        class: %shapecode_twig_collector.twig_extension.collector.class%
        tags:
            - { name: twig.extension }
